events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;
    client_max_body_size 50m;

    # Proxy headers communs
    proxy_http_version 1.1;
    proxy_set_header Upgrade        $http_upgrade;
    proxy_set_header Connection     'upgrade';
    proxy_set_header Host           $host;
    proxy_set_header X-Real-IP      $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 300s;

    # ─── HTTP : redirect HTTPS + ACME challenge certbot ───────────────────────
    server {
        listen 80;
        server_name staging.wiki.tn dashboard.wiki.tn;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # ─── staging.wiki.tn — Frontoffice + Backend API ──────────────────────────
    server {
        listen 443 ssl;
        server_name staging.wiki.tn;

        ssl_certificate     /etc/letsencrypt/live/staging.wiki.tn/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/staging.wiki.tn/privkey.pem;
        include             /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

        # Backend REST API
        location /api/ {
            proxy_pass http://backend:8089/api/;
        }

        # Fichiers uploadés (images produits, réparation...)
        location /uploads/ {
            proxy_pass http://backend:8089/uploads/;
        }

        # Frontoffice Next.js
        location / {
            proxy_pass http://frontoffice:3000;
        }
    }

    # ─── dashboard.wiki.tn — Backoffice Admin ─────────────────────────────────
    server {
        listen 443 ssl;
        server_name dashboard.wiki.tn;

        ssl_certificate     /etc/letsencrypt/live/staging.wiki.tn/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/staging.wiki.tn/privkey.pem;
        include             /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

        location / {
            proxy_pass http://backoffice:3000;
        }
    }
}
