package api.tn.wiki.entity;

public enum OrderStatus {
    PENDING,
    CONFIRMED,
    SHIPPED,
    DELIVERED,
    CANCELLED,
    DELIVERED_TO_STORE,
    EXCHANGE,
    IN_DELIVERY_ARAMEX,
    SMT,
    ARTICLE_BEING_PURCHASED,
    AWAITING_RESTOCK,
    PC_BEING_ASSEMBLED,
    ORDER_BEING_PICKED_UP,
    TRANSFERRED_TO_STORE_FACILITY_PAYMENT,
    TRANSFERRED_TO_STORE_CHECK_PAYMENT,
    UNREACHABLE_NUMBER,
    AWAITING_AVAILABILITY_CHECK,
    ORDER_ARRIVED_AT_STORE,
    IN_DELIVERY_OWN_MEANS,
    AWAITING_CLIENT_RESPONSE,
    AWAITING_PAYMENT,
    PAID
}
